"use client";
import {FormEvent,useState} from "react";
import {Eye,EyeOff,LockKeyhole,Mail,User,ArrowRight} from "lucide-react";
import StoreHeader from "@/components/StoreHeader";
export default function CustomerAuthForm({mode}:{mode:"login"|"signup"}){
 const [name,setName]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[visible,setVisible]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{const r=await fetch("/api/customer-auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:mode,name,email,password})});const j=await r.json();if(!r.ok)throw Error(j.message||"Impossible de continuer.");window.location.assign("/account")}catch(e){setError(e instanceof Error?e.message:"Erreur de connexion")}finally{setBusy(false)}}
 return <main className="exact-page"><StoreHeader/><section style={{minHeight:"70vh",display:"grid",placeItems:"center",padding:"50px 18px",background:"linear-gradient(145deg,#f1f7f5,#f7f9fd)"}}><div style={{width:"100%",maxWidth:440,background:"white",borderRadius:22,padding:"clamp(24px,5vw,42px)",boxShadow:"0 20px 65px #143a3120",border:"1px solid #e1eae6"}}>
 <div style={{width:52,height:52,borderRadius:15,background:"#e7f7ef",display:"grid",placeItems:"center",color:"#167a50",marginBottom:22}}><LockKeyhole size={25}/></div>
 <h1 style={{fontSize:29,fontWeight:800,color:"#172b36",margin:"0 0 10px"}}>{mode==="login"?"Bienvenue sur LHAWTA":"Créer votre compte"}</h1><p style={{color:"#697b87",fontSize:14,lineHeight:1.6,marginBottom:25}}>{mode==="login"?"Connectez-vous pour retrouver votre espace client.":"Rejoignez LHAWTA pour gérer votre profil et vos commandes."}</p>
 <form onSubmit={submit} style={{display:"grid",gap:16}}>
 {mode==="signup"&&<label style={{display:"grid",gap:7,fontWeight:650,fontSize:13}}>Nom complet<div style={{position:"relative"}}><User size={18} style={{position:"absolute",left:14,top:15,color:"#8b9ba3"}}/><input required minLength={2} value={name} onChange={e=>setName(e.target.value)} placeholder="Votre nom" style={{width:"100%",height:48,paddingLeft:43,border:"1px solid #dce5e5",borderRadius:10,fontSize:16}}/></div></label>}
 <label style={{display:"grid",gap:7,fontWeight:650,fontSize:13}}>Adresse email<div style={{position:"relative"}}><Mail size={18} style={{position:"absolute",left:14,top:15,color:"#8b9ba3"}}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nom@exemple.com" style={{width:"100%",height:48,paddingLeft:43,border:"1px solid #dce5e5",borderRadius:10,fontSize:16}}/></div></label>
 <label style={{display:"grid",gap:7,fontWeight:650,fontSize:13}}>Mot de passe<div style={{position:"relative"}}><LockKeyhole size={18} style={{position:"absolute",left:14,top:15,color:"#8b9ba3"}}/><input required minLength={8} type={visible?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="8 caractères minimum" style={{width:"100%",height:48,paddingLeft:43,paddingRight:45,border:"1px solid #dce5e5",borderRadius:10,fontSize:16}}/><button type="button" onClick={()=>setVisible(!visible)} aria-label={visible?"Masquer":"Afficher"} style={{position:"absolute",right:10,top:9,border:0,background:"transparent",padding:5,cursor:"pointer"}}>{visible?<EyeOff size={20}/>:<Eye size={20}/>}</button></div></label>
 {error&&<p role="alert" style={{color:"#b42318",fontSize:13}}>{error}</p>}
 <button disabled={busy} type="submit" style={{height:50,border:0,borderRadius:11,background:"#168254",color:"white",fontWeight:750,fontSize:15,cursor:"pointer",display:"flex",justifyContent:"center",alignItems:"center",gap:9}}>{busy?"Veuillez patienter…":mode==="login"?"Se connecter":"Créer mon compte"}<ArrowRight size={18}/></button>
 </form><p style={{textAlign:"center",marginTop:24,fontSize:14,color:"#647580"}}>{mode==="login"?"Pas encore de compte ? ":"Déjà un compte ? "}<a style={{color:"#117a51",fontWeight:750}} href={mode==="login"?"/signup":"/login"}>{mode==="login"?"Créer un compte":"Se connecter"}</a></p>
 {mode==="login"&&<p style={{textAlign:"center",marginTop:15,fontSize:13}}><a href="/admin/orders" style={{color:"#546a78",textDecoration:"underline",textUnderlineOffset:3}}>Accès administrateur — Gestion des commandes</a></p>}
 </div></section></main>
}
